<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_jenis extends CI_Model
{

    public $table = 'tb_jenis';
    public $id = 'ID_JENIS';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all_asc()
    {
        return $this->db->get($this->table)->result();
    }
    // function get_count()
    // {
    //     $this->db->select(" TAHUN_DATA, COUNT(IF(JENIS_DATA='AI',1,NULL)) 'Artificial Intelegence', 
    //     COUNT(IF(JENIS_DATA='ANDROID',1,NULL)) 'Android', COUNT(IF(JENIS_DATA='CODEIGNITER',1,NULL)) 
    //     'Codeigniter',COUNT(IF(JENIS_DATA='PHPNATIVE',1,NULL)) 'PHP Native'");
    //     $this->db->group_by('tb_data.TAHUN_DATA');
    //     return $this->db->get('tb_data')->result();
    // }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_JENIS', $q);
	$this->db->or_like('BIDANG_DATA', $q);
	$this->db->or_like('JENIS_DATA', $q);
	$this->db->or_like('KET_JENIS', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function getByBidang($id)
    {
        $this->db->where('BIDANG_DATA',$id);
        return $this->db->get('tb_jenis');
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_JENIS', $q);
	$this->db->or_like('BIDANG_DATA', $q);
	$this->db->or_like('JENIS_DATA', $q);
	$this->db->or_like('KET_JENIS', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_jenis.php */
/* Location: ./application/models/M_jenis.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-12 05:41:38 */
/* http://harviacode.com */